version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: youon-api
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    working_dir: /code/apps/api
    env_file:
      - .env

  frontend:
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile
    container_name: youon-frontend
    ports:
      - "3000:3000"
    working_dir: /app
    volumes:
      - ./apps/frontend:/app
      - /app/node_modules
    environment:
      - NEXT_PUBLIC_API_BASE=http://localhost:8000/v1
      - NODE_ENV=development
    depends_on:
      - api

  orquestrador:
    build:
      context: .
      dockerfile: Dockerfile.orquestrador
    container_name: youon-orquestrador
    working_dir: /app
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    depends_on:
      - api
    restart: unless-stopped
