version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: youon-api
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    environment:
      - DB_HOST=psql-database-mapping.postgres.database.azure.com
      - DB_NAME=db_youon_intelligence
      - DB_USER=guilherme@psql-database-mapping
      - DB_PASS=SenhaForteAqui
      - DB_PORT=5432
      - DB_SCHEMA=intel_lead       
      - DB_SSLMODE=require    
    working_dir: /code/apps/api

  frontend:
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile
    container_name: youon-frontend
    ports:
      - "3000:3000"
    working_dir: /app
    volumes:
      - ./apps/frontend:/app
      - /app/node_modules
    environment:
      # 🟢 IMPORTANTE: use localhost no navegador (host) para funcionar fora do container
      - NEXT_PUBLIC_API_BASE=http://localhost:8000
      - NODE_ENV=development
    depends_on:
      - api
